[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/comments"
  to = "/.netlify/functions/comments"
  status = 200

[[redirects]]
  from = "/api/visits"
  to = "/.netlify/functions/visits"
  status = 200

[[redirects]]
  from = "/api/admin/comments"
  to = "/.netlify/functions/admin-comments"
  status = 200

[[redirects]]
  from = "/api/admin/action"
  to = "/.netlify/functions/admin-comment-action"
  status = 200

[[redirects]]
  from = "/api/admin/login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin/logout"
  to = "/.netlify/functions/admin-logout"
  status = 200
