backend:
  name: git-gateway
  branch: main
  site_domain: mojadoza.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "postavke"
    label: "Postavke Sajta"
    files:
      - file: "content/izgled.json"
        label: "Izgled Sajta"
        name: "izgled"
        fields:
          - { label: "Pozadinska Slika", name: "pozadina", widget: "image", required: false }
          - { label: "Pozadinska Muzika (MP3)", name: "muzika", widget: "file", required: false }

  - name: "horoskop"
    label: "Mesečni Horoskop"
    folder: "content/horoskop"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-horoskop"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Ovan", name: "ovan", widget: "markdown", required: false }
      - { label: "Bik", name: "bik", widget: "markdown", required: false }
      - { label: "Blizanci", name: "blizanci", widget: "markdown", required: false }
      - { label: "Rak", name: "rak", widget: "markdown", required: false }
      - { label: "Lav", name: "lav", widget: "markdown", required: false }
      - { label: "Devica", name: "devica", widget: "markdown", required: false }
      - { label: "Vaga", name: "vaga", widget: "markdown", required: false }
      - { label: "Škorpija", name: "skorpija", widget: "markdown", required: false }
      - { label: "Strelac", name: "strelac", widget: "markdown", required: false }
      - { label: "Jarac", name: "jarac", widget: "markdown", required: false }
      - { label: "Vodolija", name: "vodolija", widget: "markdown", required: false }
      - { label: "Ribe", name: "ribe", widget: "markdown", required: false }

  - name: "zanimljivosti"
    label: "Zanimljivosti & Tekstovi"
    folder: "content/zanimljivosti"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naslov Teksta", name: "title", widget: "string" }
      - { label: "Kratak Opis", name: "description", widget: "string" }
      - { label: "Sadržaj Teksta", name: "body", widget: "markdown" }

  # BLOG
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naslov Bloga", name: "title", widget: "string" }
      - { label: "Kratak Opis", name: "description", widget: "text", required: false }
      - { label: "Naslovna Slika", name: "image", widget: "image", required: false }
      - { label: "Sadržaj Bloga", name: "body", widget: "markdown" }

  - name: "privatna_citanja"
    label: "Privatna Čitanja"
    files:
      - name: "info"
        label: "Uredi Informacije za Čitanja"
        file: "content/privatna-citanja.json"
        fields:
          - { label: "Naslov Sekcije", name: "title", widget: "string", default: "Zakažite Vaše Lično Čitanje" }
          - { label: "Opis / Tekst", name: "description", widget: "markdown" }
          - { label: "Kontakt Email", name: "email", widget: "string", default: "kontakt@mojadoza.com" }
